export const crewTemplates = [
  {
    id: "engineer",
    name: "Engineer",
    role: "Field Utility",
    maxHp: 108,
    hp: 108,
    attack: 14,
    speed: 9,
    color: "#f4a259",
    attackName: "Plasma Cutter",
    attackText: "Deals solid single-target damage and builds skill charge.",
    attackTags: ["Damage", "Skill Gain"],
    skillName: "Deploy Turret",
    skillCost: 85,
    passive: "Strikes armored targets harder.",
    skillText: "Fires an opening burst, then summons a turret that follows up for 3 rounds.",
    skillTags: ["Damage", "Buff"],
    icon: "EN",
    skillIcon: "./assets/game-icons/gear.png",
  },
  {
    id: "hacker",
    name: "Hacker",
    role: "Control Specialist",
    maxHp: 82,
    hp: 82,
    attack: 11,
    speed: 14,
    color: "#74f2ce",
    attackName: "Shock Pulse",
    attackText: "Light single-target damage with faster skill generation against drones.",
    attackTags: ["Damage", "Skill Gain"],
    skillName: "System Breach",
    skillCost: 85,
    passive: "Builds extra skill against drones.",
    skillText: "Heavy breach damage that locks one enemy and lowers its defense.",
    skillTags: ["Damage", "Debuff"],
    icon: "HK",
    skillIcon: "./assets/game-icons/brain.png",
  },
  {
    id: "medic",
    name: "Medic",
    role: "Recovery Support",
    maxHp: 90,
    hp: 90,
    attack: 9,
    speed: 11,
    color: "#f76e6e",
    attackName: "Sidearm Shot",
    attackText: "Low damage attack that still builds the Medic's skill bar.",
    attackTags: ["Damage", "Skill Gain"],
    skillName: "Emergency Patch",
    skillCost: 100,
    passive: "Removes poison and radiation.",
    skillText: "Heals a heavy amount and cleanses one ally.",
    skillTags: ["Heal", "Cleanse"],
    icon: "MD",
    skillIcon: "./assets/game-icons/radiation.png",
  },
  {
    id: "navigator",
    name: "Navigator",
    role: "Signal Tactician",
    maxHp: 94,
    hp: 94,
    attack: 12,
    speed: 13,
    color: "#8fb8ff",
    attackName: "Signal Dart",
    attackText: "Balanced attack that keeps the priority specialist moving.",
    attackTags: ["Damage", "Skill Gain"],
    skillName: "Route Override",
    skillCost: 90,
    passive: "Exploits fast targets more reliably.",
    skillText: "Grants the whole crew speed, attack boost, and a burst of skill charge.",
    skillTags: ["Buff", "Priority"],
    icon: "NV",
    skillIcon: "./assets/game-icons/route.png",
  },
];

export const itemCatalog = {
  medGel: {
    id: "medGel",
    name: "Med Gel",
    kind: "heal",
    amount: 34,
    desc: "Restores HP to one crew member.",
    color: "#ff7f96",
    icon: "./assets/game-icons/radiation.png",
    price: 28,
    explainType: "heal",
  },
  overchargeCell: {
    id: "overchargeCell",
    name: "Overcharge Cell",
    kind: "buff",
    stat: "attack",
    amount: 7,
    duration: 2,
    desc: "Boosts attack for two turns.",
    color: "#ffd166",
    icon: "./assets/game-icons/boost.png",
    price: 35,
    explainType: "buff",
  },
  shieldBattery: {
    id: "shieldBattery",
    name: "Shield Battery",
    kind: "shield",
    amount: 0.45,
    duration: 2,
    desc: "Cuts incoming damage for two turns.",
    color: "#90e0ef",
    icon: "./assets/game-icons/target.png",
    price: 32,
    explainType: "shield",
  },
  focusInjector: {
    id: "focusInjector",
    name: "Focus Injector",
    kind: "skill",
    amount: 40,
    desc: "Fills part of the skill bar.",
    color: "#c77dff",
    icon: "./assets/game-icons/time.png",
    price: 40,
    explainType: "skill",
  },
};

export const enemyArchetypes = {
  securityDrone: {
    id: "securityDrone",
    name: "Security Drone",
    type: "drone",
    maxHp: 42,
    attack: 11,
    speed: 12,
    weakness: "hacker",
    color: "#9ae6b4",
    desc: "Balanced patrol unit with scanner fire.",
  },
  maintenanceMech: {
    id: "maintenanceMech",
    name: "Maintenance Mech",
    type: "machine",
    maxHp: 62,
    attack: 13,
    speed: 8,
    weakness: "engineer",
    color: "#f6bd60",
    armor: 4,
    desc: "Slow armored frame built for industrial yards.",
  },
  raiderScavenger: {
    id: "raiderScavenger",
    name: "Raider Scavenger",
    type: "human",
    maxHp: 48,
    attack: 15,
    speed: 15,
    weakness: "navigator",
    color: "#f28482",
    desc: "Fast looter who pressures weak targets.",
  },
  bioExperiment: {
    id: "bioExperiment",
    name: "Bio-Experiment",
    type: "bio",
    maxHp: 54,
    attack: 12,
    speed: 10,
    weakness: "medic",
    color: "#b8f2e6",
    inflicts: "poison",
    desc: "Unstable lab organism that spreads poison.",
  },
};

export const stages = [
  {
    id: "stage1",
    index: 0,
    name: "Transit Hub",
    subtitle: "Emergency platform beneath the dustline",
    theme: "Tutorial pressure, drones, and first survivors.",
    backdrop: "transit",
    hordes: [
      ["securityDrone", "securityDrone"],
      ["securityDrone", "maintenanceMech"],
    ],
    boss: {
      id: "bossTransit",
      name: "Broken Security Captain",
      base: "securityDrone",
      maxHp: 98,
      attack: 16,
      speed: 13,
      weakness: "hacker",
      color: "#6ede8a",
    },
    reward: { scrap: 50, items: ["medGel"] },
    mapX: 10,
    mapY: 56,
    mapIcon: "./assets/game-icons/scan.png",
  },
  {
    id: "stage2",
    index: 1,
    name: "Mining Colony",
    subtitle: "Ore tunnels and rail cranes",
    theme: "Armor checks, unstable machinery, tighter resources.",
    backdrop: "mining",
    hordes: [
      ["maintenanceMech", "securityDrone"],
      ["maintenanceMech", "maintenanceMech"],
    ],
    boss: {
      id: "bossMining",
      name: "Loader Mech Tyrant",
      base: "maintenanceMech",
      maxHp: 118,
      attack: 18,
      speed: 9,
      weakness: "engineer",
      color: "#ffb703",
    },
    reward: { scrap: 65, items: ["shieldBattery"] },
    mapX: 30,
    mapY: 20,
    mapIcon: "./assets/game-icons/gear.png",
  },
  {
    id: "stage3",
    index: 2,
    name: "Market Dome",
    subtitle: "A civilian plaza turned war corridor",
    theme: "Fast enemies, item pressure, human desperation.",
    backdrop: "market",
    hordes: [
      ["raiderScavenger", "raiderScavenger"],
      ["raiderScavenger", "securityDrone", "maintenanceMech"],
    ],
    boss: {
      id: "bossMarket",
      name: "Raider Warlord",
      base: "raiderScavenger",
      maxHp: 128,
      attack: 19,
      speed: 16,
      weakness: "navigator",
      color: "#f94144",
    },
    reward: { scrap: 75, items: ["overchargeCell"] },
    mapX: 52,
    mapY: 62,
    mapIcon: "./assets/game-icons/signal.png",
  },
  {
    id: "stage4",
    index: 3,
    name: "Research Hospital",
    subtitle: "Containment glass and emergency lighting",
    theme: "Status effects, horror tone, harsher choices.",
    backdrop: "hospital",
    hordes: [
      ["bioExperiment", "bioExperiment"],
      ["bioExperiment", "raiderScavenger", "maintenanceMech"],
    ],
    boss: {
      id: "bossHospital",
      name: "Escaped Bio-Core",
      base: "bioExperiment",
      maxHp: 138,
      attack: 20,
      speed: 11,
      weakness: "medic",
      color: "#80ed99",
    },
    reward: { scrap: 90, items: ["focusInjector"] },
    mapX: 73,
    mapY: 24,
    mapIcon: "./assets/game-icons/radiation.png",
  },
  {
    id: "stage5",
    index: 4,
    name: "Central Rail Core",
    subtitle: "MOTHER RAIL's command chamber",
    theme: "Everything converges under the colony AI.",
    backdrop: "core",
    hordes: [
      ["securityDrone", "raiderScavenger", "bioExperiment"],
      ["maintenanceMech", "bioExperiment", "securityDrone"],
    ],
    boss: {
      id: "bossCore",
      name: "MOTHER RAIL Avatar",
      base: "securityDrone",
      maxHp: 170,
      attack: 23,
      speed: 14,
      weakness: "navigator",
      color: "#7b9cff",
    },
    reward: { scrap: 125, items: ["medGel", "overchargeCell"] },
    mapX: 88,
    mapY: 52,
    mapIcon: "./assets/game-icons/rocket.png",
  },
];

export const backdrops = {
  transit: {
    name: "Transit Hub",
    colors: ["#09131d", "#18354f", "#8d99ae"],
  },
  mining: {
    name: "Mining Colony",
    colors: ["#1d0f08", "#5f331f", "#f4a261"],
  },
  market: {
    name: "Market Dome",
    colors: ["#110b1c", "#5a189a", "#ff4d6d"],
  },
  hospital: {
    name: "Research Hospital",
    colors: ["#0b1f26", "#1b4965", "#a9d6e5"],
  },
  core: {
    name: "Central Rail Core",
    colors: ["#090914", "#263859", "#7b9cff"],
  },
};
